In [9]:
#1.Create a 1D array from a list.
import numpy as np
import pandas as pd
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
#2.Create a 3x3 array of zeros.
arr_zero = np.zeros((3,3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#3. Create a 2x2 array of ones.
arr_one = np.ones((2,2))
arr_one

array([[1., 1.],
       [1., 1.]])

In [11]:
#4. Generate array from 0 to 10 (exclusive).
arr_ex = np.arange(0,10,1)
arr_ex

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#5. Create 5 evenly spaced numbers between 0 and 1.
arr_sp = np.linspace(0,1,5)
arr_sp

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
#6. Create a 4x4 identity matrix.
arr_id = np.eye(4) 
print(arr_id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#7. Reshape 1D array to 2D.
data = np.array([1,2,3,4,5,6])
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#8. Get the shape and dtype of an array.
data1= np.array([[1,2,3,4,5,6]])
print ("shape is:",data1.shape)
print ("dtype is:",data1.dtype)

shape is: (1, 6)
dtype is: int32


In [39]:
#9. Reverse a NumPy array.
data = np.array([1,2,3,4,5,6])
rev_data = data [::-1]
rev_data 

array([6, 5, 4, 3, 2, 1])

In [41]:
#10. Extract even numbers from an array.
data = np.array([1,2,3,4,5,6])
even_data = data [data % 2 ==0]
even_data 

array([2, 4, 6])

In [65]:
#11. Find the max in each row.
data2= np.random.rand(3,4)
print("matrix is:\n",data2)
print("max value from each rows:\n",data2.max(axis = 1))

matrix is:
 [[0.30160411 0.78737647 0.66264215 0.41316855]
 [0.91665456 0.76770301 0.20332207 0.19596626]
 [0.08702845 0.11385648 0.49156248 0.17200999]]
max value from each rows:
 [0.78737647 0.91665456 0.49156248]


In [75]:
#12. Compute the mean, std, and median of an array.
data = np.array([1,2,3,9,5,6,7])
print ("mean is:",np.mean(data))
print ("standard deviation is:",np.std(data))
print ("median is:",np.median(data))

mean is: 4.714285714285714
standard deviation is: 2.657296462534039
median is: 5.0


In [81]:
#13. Stack two arrays vertically.
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
stack_arr = np.vstack((arr1,arr2))
stack_arr

array([[1, 2, 3],
       [1, 2, 3]])

In [83]:
#14. Stack two arrays horizontally.
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
stack_arr = np.hstack((arr1,arr2))
stack_arr

array([1, 2, 3, 1, 2, 3])

In [41]:
#15. Find the unique values and their counts.
val = np.array([1,2,3,3,4,5,6,2,4,7,8])
uni_val , counts = np.unique(val,return_counts = True)
print(f"Unique value:,{uni_val},Counts:,{counts}")

Unique value:,[1 2 3 4 5 6 7 8],Counts:,[1 2 2 2 1 1 1 1]


In [43]:
#16. Replace NaN with column means.
df = pd.DataFrame({'A':[4,6,np.nan,9,2,np.nan],
                   'B':[3,7,1,np.nan,8,np.nan]})
data_m = df.mean()
print("Original dataframe:\n",df)
print("\nModified DataFrame:\n",df.fillna(data_m))

Original dataframe:
      A    B
0  4.0  3.0
1  6.0  7.0
2  NaN  1.0
3  9.0  NaN
4  2.0  8.0
5  NaN  NaN

Modified DataFrame:
       A     B
0  4.00  3.00
1  6.00  7.00
2  5.25  1.00
3  9.00  4.75
4  2.00  8.00
5  5.25  4.75


In [49]:
#17. Get index of min and max values.
value = np.array([10,2,3,39,57,2,7])
print("Index of minimum value:",np.argmin(value))
print("Index of maximum value:",np.argmax(value))

Index of minimum value: 1
Index of maximum value: 4


In [53]:
#18. Create a 3D array of random integers.
arr_3d = np.random.randint(0,10,size=(3,4,3))
arr_3d

array([[[5, 8, 4],
        [1, 9, 7],
        [5, 7, 7],
        [6, 2, 2]],

       [[5, 9, 9],
        [8, 0, 1],
        [7, 0, 2],
        [2, 7, 7]],

       [[0, 4, 0],
        [1, 9, 4],
        [8, 3, 2],
        [3, 2, 1]]])

In [57]:
#19. Use np.where() to replace values.
data_s = np.array([17,26,30,49,53,62])
data_m = np.where(data_s % 2 == 0,0,data_s)
data_m

array([17,  0,  0, 49, 53,  0])